[2023-11-21T17:45:11.879+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: competition.train_model manual__2023-11-21T12:38:15.214903+00:00 [queued]>
[2023-11-21T17:45:11.927+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: competition.train_model manual__2023-11-21T12:38:15.214903+00:00 [queued]>
[2023-11-21T17:45:11.928+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T17:45:12.008+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-21 12:38:15.214903+00:00
[2023-11-21T17:45:12.027+0500] {standard_task_runner.py:57} INFO - Started process 23546 to run task
[2023-11-21T17:45:12.043+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'competition', 'train_model', 'manual__2023-11-21T12:38:15.214903+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/competition_score.py', '--cfg-path', '/tmp/tmpw7iweflr']
[2023-11-21T17:45:12.051+0500] {standard_task_runner.py:85} INFO - Job 33: Subtask train_model
[2023-11-21T17:45:12.398+0500] {task_command.py:416} INFO - Running <TaskInstance: competition.train_model manual__2023-11-21T12:38:15.214903+00:00 [running]> on host Acer
[2023-11-21T17:45:12.995+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='makar' AIRFLOW_CTX_DAG_ID='competition' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T12:38:15.214903+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T12:38:15.214903+00:00'
[2023-11-21T17:45:13.007+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-21T17:45:13.010+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/makar/MLops_3/scripts/train_model.py']
[2023-11-21T17:45:13.061+0500] {subprocess.py:86} INFO - Output:
[2023-11-21T17:45:34.387+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-21T17:45:34.390+0500] {subprocess.py:93} INFO -   File "/home/makar/MLops_3/scripts/train_model.py", line 12, in <module>
[2023-11-21T17:45:34.391+0500] {subprocess.py:93} INFO -     train_df = pd.read_csv('/home/makar/MLops_3/models/data_train.csv')
[2023-11-21T17:45:34.392+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-11-21T17:45:34.394+0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-21T17:45:34.395+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
[2023-11-21T17:45:34.396+0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-21T17:45:34.397+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[2023-11-21T17:45:34.398+0500] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-11-21T17:45:34.399+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
[2023-11-21T17:45:34.400+0500] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-11-21T17:45:34.405+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
[2023-11-21T17:45:34.407+0500] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-11-21T17:45:34.408+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
[2023-11-21T17:45:34.409+0500] {subprocess.py:93} INFO -     self.handles = get_handle(
[2023-11-21T17:45:34.409+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
[2023-11-21T17:45:34.410+0500] {subprocess.py:93} INFO -     handle = open(
[2023-11-21T17:45:34.411+0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/makar/MLops_3/models/data_train.csv'
[2023-11-21T17:45:36.226+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-21T17:45:36.333+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-21T17:45:36.383+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=competition, task_id=train_model, execution_date=20231121T123815, start_date=20231121T124511, end_date=20231121T124536
[2023-11-21T17:45:36.596+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 23546)
[2023-11-21T17:45:36.680+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:45:36.808+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
